### ISSUE TITLE
Quotation marks not working on iOS

### ISSUE THREAD

**Issue by JcbSm** [discord-akairo/discord-akairo#79]
When using the `split: "quoted"` option, the quotation marks which are used on iOS (maybe other devices, I'm not sure) aren't recognised as quotation marks. 

When command is done from iPhone:
![image](https://user-images.githubusercontent.com/49797894/65082846-dc901100-d99e-11e9-926f-8989a6d6c8bb.png)

When done normally:
![image](https://user-images.githubusercontent.com/49797894/65082870-eca7f080-d99e-11e9-97f1-ce1fe0fedffd.png)

Thanks :D

**Comment by Reseq64** [comment]
This is expected behavior, iOS' quotes are another Unicode than the one on Android, Windows and some other OS, so it's totally normal, just use normal quotes, and not iOS' one. Or make a PR to make it accept this Unicode character too.

**Comment by GamesProSeif** [comment]
Just for reference to show difference and if you're going to make a PR or anything.
```yml
- normal quote:
    name: QUOTATION MARK
    symbol: \"
    unicode: \u0022
- left quote:
    name: LEFT DOUBLE QUOTATION MARK
    symbol: “
    unicode: \u201C
- right quote:
    name: RIGHT DOUBLE QUOTATION MARK
    symbol: ”
    unicode: \u201D
```
